// analytics/analyticsConfig.js
module.exports = {
  // Financial thresholds
  PROFIT_WARNING: 5,
  PROFIT_HEALTHY: 15,
  CRITICAL_DEBT: 10000,
  HIGH_DEBT: 5000,
  MEDIUM_DEBT: 1000,
  LIQUIDITY_RATIO: 0.3,
  PAYOUT_COVERAGE_WARNING: 100,
  PAYOUT_COVERAGE_CRITICAL: 70,

  // Farmer risk thresholds
  INACTIVE_DAYS_HIGH: 30,
  INACTIVE_DAYS_MEDIUM: 14,
  INACTIVE_DAYS_LOW: 7,
  PRODUCTION_DROP_HIGH: 0.5,
  PRODUCTION_DROP_MEDIUM: 0.8,
  LOW_DELIVERY_FREQUENCY: 5,
  RISK_SCORE_CRITICAL: 9,
  RISK_SCORE_HIGH: 6,
  RISK_SCORE_MEDIUM: 3,

  // Inventory thresholds
  FAST_MOVING_DAILY: 10,
  SLOW_MOVING_DAILY: 2,
  STOCKOUT_CRITICAL: 3,
  STOCKOUT_URGENT: 7,
  STOCKOUT_MEDIUM: 14,

  // Operations thresholds
  COLLECTION_EFFICIENCY_GOOD: 80,
  COLLECTION_EFFICIENCY_WARNING: 60,
  OFFLINE_DEVICE_WARNING: 1,

  // Decision priorities
  PRIORITY_CRITICAL: 1,
  PRIORITY_HIGH: 2,
  PRIORITY_MEDIUM: 3,
  PRIORITY_LOW: 4,

  // Forecast
  MIN_HISTORICAL_MONTHS: 4,
  MIN_DATA_POINTS_FOR_FORECAST: 4,
  CONFIDENCE_R2_THRESHOLD: 0.6,
  DEFAULT_ALPHA: 0.2,

  // Health scoring weights (sum to 100)
  HEALTH_WEIGHT_FINANCIAL: 35,
  HEALTH_WEIGHT_OPERATIONS: 25,
  HEALTH_WEIGHT_FARMERS: 20,
  HEALTH_WEIGHT_INVENTORY: 10,
  HEALTH_WEIGHT_FORECAST: 10,

  // Health thresholds
  HEALTH_GOOD: 80,
  HEALTH_FAIR: 60,
  HEALTH_WARNING: 40,

  // Benchmark
  BENCHMARK_SEASONAL_MONTHS: 12,
};